package bai.zsj.com;

import org.testng.Assert;
import org.testng.annotations.Test;

public class Test1 {
  @Test
  public void f() {
	  System.out.println("成功1111");
	  int a=2,b=1;
	  int c=a/b;
  }
  @Test
  public void f2() throws Exception {
	  System.out.println("成功3333");
//	  throw new Exception();
  }
  @Test
  public void f3() throws Exception {
	  System.out.println("成功3333");
//	  throw new Exception();
  }
  @Test
  public void f4() throws Exception {
	  System.out.println("成功3333");
//	  throw new Exception();
  }
  @Test
  public void f5() throws Exception {
	  System.out.println("成功3333");
//	  throw new Exception();
  }
}
